title:            wkgg Another Blog
description:      This is my personal blog, Talking something I want to talk
url:              # Site url.
signoff:          wkgg
disqus_shortname: wkgg
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /
  - name:         Email
    url:          mailto:wky1991@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/wkgg
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
